/**
 * Client app: the side-chat controller.
 *
 * Owns the chat panel for the selected artifact and the send/undo behavior. It
 * calls `api.chatEdit` / `api.undoEdit` (the per-session editing endpoints) and
 * never triggers a full re-analysis.
 */
export const CHAT_LINES: string[] = [
  "function renderChat() {",
  "  var box = $('chat'); if (!box) return;",
  "  box.innerHTML = '';",
  "  if (!state.ready) { box.classList.add('hidden'); return; }",
  "  box.classList.remove('hidden');",
  "  var id = state.selected;",
  "  if (!EDITABLE[id]) {",
  "    box.appendChild(el('h3', 'chat-title', 'Chat'));",
  "    box.appendChild(el('p', 'muted chat-help', 'Chat editing is available for generated text artifacts only.'));",
  "    return;",
  "  }",
  "  box.appendChild(el('h3', 'chat-title', 'Chat about ' + EDITABLE[id]));",
  "  box.appendChild(el('p', 'muted chat-help', CHAT_HELP));",
  "  if (statusOf(id) !== 'generated') {",
  "    box.appendChild(el('p', 'chat-empty', 'Generate ' + EDITABLE[id] + ' first, then you can edit it here.'));",
  "    return;",
  "  }",
  "  var msgs = el('div', 'chat-messages'); msgs.id = 'chat-messages';",
  "  var list = state.chatMessages[id] || [];",
  "  if (list.length === 0 && !state.chatLoading) { msgs.appendChild(el('p', 'chat-empty', 'No messages yet. Try: \"Make this shorter.\"')); }",
  "  for (var i = 0; i < list.length; i++) { var m = el('div', 'chat-msg chat-' + list[i].role); m.appendChild(el('div', 'chat-bubble', list[i].content)); msgs.appendChild(m); }",
  "  if (state.chatLoading) { var lm = el('div', 'chat-msg chat-assistant'); lm.appendChild(el('div', 'chat-bubble', 'Editing…')); msgs.appendChild(lm); }",
  "  box.appendChild(msgs);",
  "  var ta = el('textarea', 'chat-input'); ta.id = 'chat-input'; ta.rows = 2; ta.placeholder = 'Ask for an edit to ' + EDITABLE[id] + '…'; ta.disabled = state.chatLoading;",
  "  box.appendChild(ta);",
  "  var row = el('div', 'chat-actions');",
  "  var send = el('button', 'btn btn-accent', 'Send'); send.type = 'button'; send.disabled = state.chatLoading;",
  "  send.addEventListener('click', function () { sendChat(id); });",
  "  row.appendChild(send);",
  "  if (state.canUndo[id]) { var u = el('button', 'btn', 'Undo last edit'); u.type = 'button'; u.disabled = state.chatLoading; u.addEventListener('click', function () { undoChat(id); }); row.appendChild(u); }",
  "  box.appendChild(row);",
  "}",
  "",
  "function sendChat(id) {",
  "  if (!state.ready || !EDITABLE[id]) return;",
  "  var ta = $('chat-input'); if (!ta) return; var msg = ta.value.trim(); if (!msg) return;",
  "  if (!state.chatMessages[id]) state.chatMessages[id] = [];",
  "  var history = state.chatMessages[id].slice();",
  "  state.chatMessages[id].push({ role: 'user', content: msg });",
  "  state.chatLoading = true; renderChat();",
  "  var payload = { artifactKey: id, message: msg, conversationHistory: history };",
  "  api.chatEdit(state.sessionId, payload)",
  "    .then(function (data) {",
  "      state.chatLoading = false;",
  "      if (data.status === 'success') {",
  "        state.chatMessages[id].push({ role: 'assistant', content: data.assistantMessage });",
  "        state.cards[id] = data.card; state.canUndo[id] = data.canUndo;",
  "        if (state.selected === id) renderPanel();",
  "        renderChat(); setStatus('success', EDITABLE[id] + ' updated.');",
  "      } else {",
  "        state.chatMessages[id].push({ role: 'assistant', content: 'Error: ' + data.message });",
  "        renderChat(); setStatus('error', 'Edit failed: ' + data.message);",
  "      }",
  "    })",
  "    .catch(function (err) { state.chatLoading = false; state.chatMessages[id].push({ role: 'assistant', content: 'Request failed.' }); renderChat(); setStatus('error', 'Request failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "}",
  "",
  "function undoChat(id) {",
  "  if (!state.ready || !EDITABLE[id]) return;",
  "  state.chatLoading = true; renderChat();",
  "  api.undoArtifactEdit(state.sessionId, { artifactKey: id })",
  "    .then(function (data) {",
  "      state.chatLoading = false;",
  "      if (data.status === 'success') {",
  "        state.cards[id] = data.card; state.canUndo[id] = data.canUndo;",
  "        if (state.selected === id) renderPanel();",
  "        renderChat(); setStatus('success', data.restored ? (EDITABLE[id] + ' reverted to the previous version.') : 'Nothing to undo.');",
  "      } else { renderChat(); setStatus('error', 'Undo failed: ' + data.message); }",
  "    })",
  "    .catch(function (err) { state.chatLoading = false; renderChat(); setStatus('error', 'Request failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "}",
  "",
];
