/**
 * Client app: the Project Command Center controller.
 *
 * Makes a project feel "already connected" so the everyday flow is
 * select-project → click an action, not paste-everything-again. It owns:
 *   - a small browser-local (localStorage) store of per-project context
 *     (spec/diff/GitHub URL) plus a summary of the last run — this is the
 *     smallest safe way to reuse inputs without any backend/persistence change;
 *   - a clearly-labeled sample project so mock/demo mode starts pre-connected;
 *   - the connected-context panel, the "context this run will use" pills, and
 *     the one-click action buttons;
 *   - launching a run via the workspace's shared `submitRun`, passing saved
 *     context instead of reading the manual form.
 *
 * It never calls the network directly (it goes through `submitRun` → `api`) and
 * holds no artifact-rendering logic (that stays in the workspace controller).
 * Emitted as source lines because the whole client is one inline script.
 */
export const COMMAND_CENTER_LINES: string[] = [
  "var CC_STORE_KEY = 'dwc.projects.v1';",
  "var CC_SAMPLE = {",
  "  projectName: 'checkout-service',",
  "  inputMode: 'manual',",
  "  requirementText: 'Add a cache for product lookups: 60s TTL, invalidate on product update, and count cache hits and misses for metrics.',",
  "  rawDiff: 'diff --git a/src/productCache.ts b/src/productCache.ts\\n+const TTL_SECONDS = 60;\\n+export async function getProduct(id) {\\n+  const cached = await cache.get(id);\\n+  if (cached) return cached;\\n+  const product = await db.products.find(id);\\n+  await cache.set(id, product, TTL_SECONDS);\\n+  return product;\\n+}',",
  "  githubUrl: 'https://github.com/demo/checkout-service/pull/128',",
  "  sample: true",
  "};",
  "",
  "function ccMode() { var w = document.querySelector('[data-ui-mode]'); return (w && w.getAttribute('data-ui-mode')) || 'mock'; }",
  "",
  "function ccRead() {",
  "  try {",
  "    var raw = window.localStorage.getItem(CC_STORE_KEY);",
  "    if (!raw) return { projects: {}, activeProject: null };",
  "    var v = JSON.parse(raw);",
  "    if (!v || typeof v !== 'object') return { projects: {}, activeProject: null };",
  "    if (!v.projects) v.projects = {};",
  "    return v;",
  "  } catch (e) { return { projects: {}, activeProject: null }; }",
  "}",
  "function ccWrite(store) { try { window.localStorage.setItem(CC_STORE_KEY, JSON.stringify(store)); } catch (e) {} }",
  "",
  "function ccActive() {",
  "  var store = ccRead();",
  "  if (store.activeProject && store.projects[store.activeProject]) return store.projects[store.activeProject];",
  "  for (var k in store.projects) { if (store.projects.hasOwnProperty(k)) return store.projects[k]; }",
  "  // Demo default: a clearly-labeled pre-connected project, mock mode only.",
  "  if (ccMode() === 'mock') return CC_SAMPLE;",
  "  return null;",
  "}",
  "",
  "function ccUpsert(ctx) {",
  "  if (!ctx || !ctx.projectName) return;",
  "  var store = ccRead();",
  "  var existing = store.projects[ctx.projectName] || {};",
  "  store.projects[ctx.projectName] = {",
  "    projectName: ctx.projectName,",
  "    inputMode: ctx.inputMode || existing.inputMode || 'manual',",
  "    requirementText: (ctx.requirementText !== undefined ? ctx.requirementText : existing.requirementText) || '',",
  "    rawDiff: (ctx.rawDiff !== undefined ? ctx.rawDiff : existing.rawDiff) || '',",
  "    githubUrl: (ctx.githubUrl !== undefined ? ctx.githubUrl : existing.githubUrl) || '',",
  "    websiteUrl: (ctx.websiteUrl !== undefined ? ctx.websiteUrl : existing.websiteUrl) || '',",
  "    notionText: (ctx.notionText !== undefined ? ctx.notionText : existing.notionText) || '',",
  "    savedAt: new Date().toISOString(),",
  "    lastRun: existing.lastRun || null",
  "  };",
  "  store.activeProject = ctx.projectName;",
  "  ccWrite(store);",
  "}",
  "",
  "function ccSetLastRun(name, info) {",
  "  if (!name) return;",
  "  var store = ccRead();",
  "  var p = store.projects[name];",
  "  if (!p) return;",
  "  p.lastRun = info;",
  "  ccWrite(store);",
  "}",
  "",
  "function ccFormCtx() {",
  "  var mode = currentMode();",
  "  var name = ($('projectName') && $('projectName').value.trim()) || '';",
  "  var ctx = { projectName: name, inputMode: mode };",
  "  if (mode === 'manual') { ctx.requirementText = $('requirementText').value; ctx.rawDiff = $('rawDiff').value; }",
  "  else if (mode === 'githubUrl') { ctx.githubUrl = $('githubUrl').value; ctx.requirementText = $('gh_requirementText').value; }",
  "  else if (mode === 'websiteContextUrl') { ctx.websiteUrl = $('websiteUrl').value; ctx.rawDiff = $('ws_rawDiff').value; }",
  "  else if (mode === 'notionText') { ctx.notionText = $('notionText').value; ctx.rawDiff = $('nt_rawDiff').value; }",
  "  return ctx;",
  "}",
  "",
  "function ccBuildPayload(ctx, targets) {",
  "  var p = { inputMode: ctx.inputMode || 'manual', projectName: ctx.projectName || '' };",
  "  p.includeFlow = true; p.includeGapReport = true;",
  "  p.includePrDescription = false; p.includeVideoScript = false; p.includeDailyUpdate = false; p.includeDailyWorkGuidance = false; p.includeTechnicalChangeBrief = false; p.includeDemoPrepLoop = false; p.includeWeeklyReview = false;",
  "  for (var i = 0; i < targets.length; i++) { if (FLAG_OF[targets[i]]) p[FLAG_OF[targets[i]]] = true; }",
  "  var m = p.inputMode;",
  "  if (m === 'manual') { p.requirementText = ctx.requirementText || ''; p.rawDiff = ctx.rawDiff || ''; }",
  "  else if (m === 'githubUrl') { p.githubUrl = ctx.githubUrl || ''; p.requirementText = ctx.requirementText || ''; }",
  "  else if (m === 'websiteContextUrl') { p.websiteUrl = ctx.websiteUrl || ''; p.rawDiff = ctx.rawDiff || ''; }",
  "  else if (m === 'notionText') { p.notionText = ctx.notionText || ctx.requirementText || ''; p.rawDiff = ctx.rawDiff || ''; }",
  "  return p;",
  "}",
  "",
  "function ccRunInfo(data) {",
  "  var g = data.overview && data.overview.guidance;",
  "  var mem = data.memory;",
  "  var memState = 'none';",
  "  if (mem && mem.snapshot) { memState = mem.loadedForThisRun ? 'loaded' : 'saved'; }",
  "  return { at: new Date().toISOString(), mode: data.mode, loopStage: g ? g.loopStage : null, memory: memState, hasPrefs: !!(mem && mem.promptPreferences) };",
  "}",
  "",
  "function ccWhen(iso) { if (!iso) return 'never'; try { return new Date(iso).toLocaleString(); } catch (e) { return iso; } }",
  "function ccCap(s) { if (!s) return ''; return s.charAt(0).toUpperCase() + s.slice(1); }",
  "function ccClip(s, n) { if (!s) return ''; s = ('' + s).replace(/\\s+/g, ' ').trim(); return s.length > n ? s.slice(0, n) + '\\u2026' : s; }",
  "",
  "function ccUsing(label, on) {",
  "  var pill = el('span', 'cc-using-item');",
  "  pill.appendChild(el('span', 'cc-dot ' + (on ? 'cc-dot-on' : 'cc-dot-off')));",
  "  pill.appendChild(el('span', null, label + ': ' + (on ? 'yes' : 'no')));",
  "  return pill;",
  "}",
  "",
  "function renderCommandCenter() {",
  "  var box = $('command-center'); if (!box) return;",
  "  box.innerHTML = '';",
  "  var ctx = ccActive();",
  "  if (!ctx) { renderCCSetup(box); return; }",
  "  box.appendChild(el('div', 'cc-eyebrow', 'Project Command Center'));",
  "  var titleRow = el('div', 'cc-title-row');",
  "  titleRow.appendChild(el('h2', null, ctx.projectName || 'Untitled project'));",
  "  var mock = ccMode() === 'mock';",
  "  var badges = el('div', 'cc-badges');",
  "  badges.appendChild(companionChip(mock ? 'companion-chip-mock' : 'companion-chip-real', mock ? 'Demo / mock data' : 'Real engine', ''));",
  "  if (ctx.sample) badges.appendChild(companionChip('', 'Sample project', ''));",
  "  titleRow.appendChild(badges);",
  "  box.appendChild(titleRow);",
  "  box.appendChild(el('p', 'muted', 'Everything this project needs is connected. Run the daily flow with one click \\u2014 no need to paste the spec or diff again.'));",
  "  var lr = ctx.lastRun || null;",
  "  var grid = el('div', 'stat-grid');",
  "  grid.appendChild(statCard('Active spec', (ctx.requirementText && ctx.requirementText.trim() !== '') ? 'Connected' : (ctx.inputMode === 'githubUrl' ? 'From GitHub' : 'Not set'), ccClip(ctx.requirementText, 80) || 'Add a requirement / spec'));",
  "  var srcVal = ctx.githubUrl ? 'GitHub PR' : ((ctx.rawDiff && ctx.rawDiff.trim() !== '') ? 'Manual diff' : 'Not set');",
  "  grid.appendChild(statCard('Source', srcVal, ctx.githubUrl || ((ctx.rawDiff && ctx.rawDiff.trim() !== '') ? 'Using the connected diff' : 'Add a PR URL or diff')));",
  "  grid.appendChild(statCard('Memory', lr ? ccCap(lr.memory) : 'Not loaded yet', lr ? ('from last run ' + ccWhen(lr.at)) : 'Your first run will build project memory'));",
  "  grid.appendChild(statCard('Last run', lr ? ccWhen(lr.at) : 'Never', (lr && lr.loopStage) ? (LOOP_STAGE_LABELS[lr.loopStage] || lr.loopStage) : 'No runs yet'));",
  "  box.appendChild(grid);",
  "  box.appendChild(el('div', 'cc-using-title', 'Context this run will use'));",
  "  var using = el('div', 'cc-using');",
  "  using.appendChild(ccUsing('Active spec', (ctx.requirementText && ctx.requirementText.trim() !== '') || ctx.inputMode === 'githubUrl'));",
  "  using.appendChild(ccUsing('GitHub source', !!ctx.githubUrl));",
  "  using.appendChild(ccUsing('Project memory', !!(lr && lr.memory && lr.memory !== 'none')));",
  "  using.appendChild(ccUsing('Prompt preferences', !!(lr && lr.hasPrefs)));",
  "  box.appendChild(using);",
  "  var actions = el('div', 'cc-actions');",
  "  var daily = el('button', 'primary-btn', 'Run Daily Work Guidance'); daily.type = 'button'; daily.id = 'cc-daily'; daily.addEventListener('click', ccRunDaily); actions.appendChild(daily);",
  "  var demo = el('button', 'btn btn-accent', 'Generate Demo / Presentation Prep'); demo.type = 'button'; demo.id = 'cc-demo'; demo.addEventListener('click', ccRunDemoPrep); actions.appendChild(demo);",
  "  var review = el('button', 'btn btn-soft', 'Generate Code Review Prep'); review.type = 'button'; review.id = 'cc-review'; review.addEventListener('click', ccRunReviewPrep); actions.appendChild(review);",
  "  var gh = el('button', 'btn btn-soft', 'Analyze Latest GitHub Work'); gh.type = 'button'; gh.id = 'cc-github';",
  "  if (ctx.githubUrl && !mock) { gh.addEventListener('click', ccRunGithub); } else { gh.disabled = true; gh.title = ctx.githubUrl ? 'Available in real mode \\u2014 fetches the live PR diff.' : 'Add a GitHub PR/commit URL in Advanced / Manual Input.'; }",
  "  actions.appendChild(gh);",
  "  var refresh = el('button', 'btn btn-soft', 'Refresh Project Context'); refresh.type = 'button'; refresh.addEventListener('click', function () { renderCommandCenter(); setStatus('idle', 'Project context refreshed.'); }); actions.appendChild(refresh);",
  "  box.appendChild(actions);",
  "  var adv = el('button', 'btn btn-soft', 'Advanced / Manual Input'); adv.type = 'button'; adv.addEventListener('click', ccOpenAdvanced);",
  "  var advWrap = el('div'); advWrap.appendChild(adv); box.appendChild(advWrap);",
  "  box.appendChild(el('p', 'note', 'MVP: connected context is remembered in your browser for this project. Manual input stays the source of truth and override.'));",
  "}",
  "",
  "function renderCCSetup(box) {",
  "  box.appendChild(el('div', 'cc-eyebrow', 'Project Command Center'));",
  "  var titleRow = el('div', 'cc-title-row'); titleRow.appendChild(el('h2', null, 'Connect project context')); box.appendChild(titleRow);",
  "  box.appendChild(el('p', 'muted', 'Connect this project once, then run Daily Work Guidance with a single click \\u2014 no pasting the spec and diff every time.'));",
  "  var ul = el('ul', 'cc-setup-list');",
  "  var items = ['Add your requirement / spec', 'Add a GitHub PR/commit URL or paste a diff', 'Save project context'];",
  "  for (var i = 0; i < items.length; i++) { var li = el('li'); li.textContent = items[i]; ul.appendChild(li); }",
  "  box.appendChild(ul);",
  "  var row = el('div', 'cc-actions');",
  "  var setup = el('button', 'primary-btn', 'Set up project'); setup.type = 'button'; setup.addEventListener('click', ccOpenAdvanced); row.appendChild(setup);",
  "  var save = el('button', 'btn btn-soft', 'Save current inputs as project'); save.type = 'button'; save.addEventListener('click', ccSaveContext); row.appendChild(save);",
  "  box.appendChild(row);",
  "}",
  "",
  "// opts: { targets: string[], selectId: string, buttonId: string }. Named so",
  "// call sites do not pass two look-alike strings positionally.",
  "function ccLaunch(ctx, opts) {",
  "  var btnId = opts.buttonId;",
  "  var btn = btnId ? $(btnId) : null; if (btn) btn.disabled = true;",
  "  var persist = {}; for (var k in ctx) { if (ctx.hasOwnProperty(k) && k !== 'sample') persist[k] = ctx[k]; }",
  "  return submitRun(ccBuildPayload(ctx, opts.targets), { selectId: opts.selectId, onSuccess: function (data) { if (persist.projectName) ccUpsert(persist); ccSetLastRun(persist.projectName, ccRunInfo(data)); renderCommandCenter(); } })",
  "    .then(function () { var b = btnId ? $(btnId) : null; if (b) b.disabled = false; });",
  "}",
  "function ccRunDaily() { var ctx = ccActive(); if (!ctx) return ccNeedProject(); ccLaunch(ctx, { targets: ['dailyWorkGuidance'], selectId: 'dailyWorkGuidance', buttonId: 'cc-daily' }); }",
  "function ccRunDemoPrep() { var ctx = ccActive(); if (!ctx) return ccNeedProject(); ccLaunch(ctx, { targets: ['demoPrepLoop'], selectId: 'demoPrepLoop', buttonId: 'cc-demo' }); }",
  "function ccRunReviewPrep() { var ctx = ccActive(); if (!ctx) return ccNeedProject(); ccLaunch(ctx, { targets: ['technicalChangeBrief'], selectId: 'technicalChangeBrief', buttonId: 'cc-review' }); }",
  "function ccRunGithub() { var ctx = ccActive(); if (!ctx || !ctx.githubUrl) return ccNeedProject(); var g = {}; for (var k in ctx) { if (ctx.hasOwnProperty(k)) g[k] = ctx[k]; } g.inputMode = 'githubUrl'; ccLaunch(g, { targets: ['dailyWorkGuidance'], selectId: 'dailyWorkGuidance', buttonId: 'cc-github' }); }",
  "function ccNeedProject() { setStatus('error', 'No project context yet. Set up a project in Advanced / Manual Input.'); ccOpenAdvanced(); }",
  "",
  "function ccOpenAdvanced() { var d = $('advanced-input'); if (d) { d.open = true; if (d.scrollIntoView) d.scrollIntoView({ behavior: 'smooth', block: 'start' }); } var r = $('requirementText'); if (r && r.offsetParent !== null) r.focus(); }",
  "function ccSaveContext() {",
  "  var ctx = ccFormCtx();",
  "  if (!ctx.projectName) { setStatus('error', 'Add a project name in Advanced / Manual Input first.'); ccOpenAdvanced(); return; }",
  "  var hasSpec = (ctx.requirementText && ctx.requirementText.trim() !== '') || (ctx.inputMode === 'githubUrl' && ctx.githubUrl && ctx.githubUrl.trim() !== '');",
  "  if (!hasSpec) { setStatus('error', 'Add a requirement / spec (or a GitHub URL) before saving.'); ccOpenAdvanced(); return; }",
  "  ccUpsert(ctx);",
  "  renderCommandCenter();",
  "  setStatus('success', 'Project context saved for ' + ctx.projectName + '. You can run it with one click now.');",
  "}",
  "function ccCaptureRun(data) {",
  "  var ctx = ccFormCtx();",
  "  if (ctx.projectName) ccUpsert(ctx);",
  "  var name = ctx.projectName || (data.memory && data.memory.projectName) || '';",
  "  ccSetLastRun(name, ccRunInfo(data));",
  "  renderCommandCenter();",
  "}",
  "function initCommandCenter() { renderCommandCenter(); }",
  "",
];
