/**
 * Client app: the analysis workspace controller.
 *
 * Owns the workspace interactions and its main view:
 *   - request builders for `/api/analyze` (initial run vs. on-demand generation);
 *   - `ingest`, which folds an analyze response into state;
 *   - the content panel + Overview + per-output action tiles;
 *   - the `generate` (on-demand) and `runAnalysis` (initial) flows.
 *
 * It calls `api.*` for the network and the shared render helpers for the DOM;
 * it never embeds endpoint URLs.
 */
export const WORKSPACE_LINES: string[] = [
  "function buildInitialPayload() {",
  "  var mode = currentMode();",
  "  var p = { inputMode: mode, projectName: $('projectName').value };",
  "  // Initial analysis runs ONLY the base understanding artifacts. Optional",
  "  // communication outputs are generated later, on demand.",
  "  p.includeFlow = true; p.includeGapReport = true;",
  "  p.includePrDescription = false; p.includeVideoScript = false; p.includeDailyUpdate = false; p.includeDailyWorkGuidance = false; p.includeTechnicalChangeBrief = false; p.includeDemoPrepLoop = false; p.includeWeeklyReview = false;",
  "  if (mode === 'manual') { p.requirementText = $('requirementText').value; p.rawDiff = $('rawDiff').value; }",
  "  else if (mode === 'githubUrl') { p.githubUrl = $('githubUrl').value; p.requirementText = $('gh_requirementText').value; }",
  "  else if (mode === 'websiteContextUrl') { p.websiteUrl = $('websiteUrl').value; p.rawDiff = $('ws_rawDiff').value; }",
  "  else if (mode === 'notionText') { p.notionText = $('notionText').value; p.rawDiff = $('nt_rawDiff').value; }",
  "  return p;",
  "}",
  "",
  "function buildGeneratePayload(targetId) {",
  "  // Re-send the resolved inputs as manual + sessionId so the engine reuses",
  "  // the session and only runs the new skill (no re-fetch, no recompute).",
  "  // projectName is included so the response's memory status still reflects the",
  "  // saved project (snapshot + stored spec summary); otherwise ingesting the",
  "  // response would blank the Project Memory panel after each generation.",
  "  var p = { inputMode: 'manual', sessionId: state.sessionId, projectName: (($('projectName') && $('projectName').value) || ''), requirementText: state.inputs.requirementText, rawDiff: state.inputs.rawDiff };",
  "  p.includeFlow = true; p.includeGapReport = true;",
  "  p.includePrDescription = false; p.includeVideoScript = false; p.includeDailyUpdate = false; p.includeDailyWorkGuidance = false; p.includeTechnicalChangeBrief = false; p.includeDemoPrepLoop = false; p.includeWeeklyReview = false;",
  "  var keep = ['prDescription','videoScript','dailyUpdate','dailyWorkGuidance','technicalChangeBrief','demoPrepLoop','weeklyReview'];",
  "  for (var i = 0; i < keep.length; i++) { if (statusOf(keep[i]) === 'generated') p[FLAG_OF[keep[i]]] = true; }",
  "  var add = [targetId].concat(DEPS[targetId] || []);",
  "  for (var j = 0; j < add.length; j++) { if (FLAG_OF[add[j]]) p[FLAG_OF[add[j]]] = true; }",
  "  return p;",
  "}",
  "",
  "function ingest(data) {",
  "  state.sessionId = data.sessionId;",
  "  state.traceId = data.traceId || null;",
  "  state.mode = data.mode;",
  "  state.inputs = data.inputs;",
  "  state.overview = data.overview;",
  "  if (data.memory) state.memory = data.memory;",
  "  if (data.sources) state.sources = data.sources;",
  "  for (var i = 0; i < data.cards.length; i++) { state.cards[data.cards[i].id] = data.cards[i]; }",
  "  state.ready = true;",
  "}",
  "",
  "function labelOf(id) {",
  "  if (id === 'overview') return 'Overview';",
  "  if (id === 'projectMemory') return 'Project Memory';",
  "  if (id === 'sources') return 'Sources';",
  "  if (id === 'safety') return 'Safety & Trust';",
  "  if (id === 'rawJson') return 'Raw JSON';",
  "  var all = BASE.concat(OUTPUTS);",
  "  for (var i = 0; i < all.length; i++) if (all[i][0] === id) return all[i][1];",
  "  return id;",
  "}",
  "",
  "function renderPanel() {",
  "  renderCompanionStatus();",
  "  var panel = $('panel');",
  "  var id = state.selected;",
  "  var grp = (id === 'overview' || id === 'sources' || id === 'safety') ? 'overview' : (GROUP_OF[id] || 'understanding');",
  "  panel.className = 'panel panel-accent-' + grp;",
  "  panel.innerHTML = '';",
  "  var head = el('div', 'panel-head');",
  "  var titleWrap = el('div');",
  "  titleWrap.appendChild(el('h2', 'panel-title', labelOf(id)));",
  "  titleWrap.appendChild(el('p', 'panel-desc', HELP[id] || VIEW_HELP[id] || ''));",
  "  head.appendChild(titleWrap);",
  "  var actions = el('div', 'panel-actions');",
  "  head.appendChild(actions);",
  "  panel.appendChild(head);",
  "  var body = el('div', 'panel-body');",
  "  panel.appendChild(body);",
  "",
  "  if (id === 'overview') { renderOverview(body); return; }",
  "  if (id === 'projectMemory') { renderMemory(body); return; }",
  "  if (id === 'sources') { renderSources(body); return; }",
  "  if (id === 'safety') { renderSafety(body); return; }",
  "",
  "  var s = statusOf(id);",
  "  if (s === 'generating') { body.appendChild(el('p', 'muted', 'Generating ' + labelOf(id) + '… this can take a little while.')); return; }",
  "  if (s === 'error') {",
  "    body.appendChild(el('p', 'status status-error', 'Error: ' + (state.errors[id] || 'generation failed')));",
  "    actions.appendChild(genButton(id, 'Try again'));",
  "    return;",
  "  }",
  "  var card = state.cards[id];",
  "  if (s === 'generated' && card) {",
  "    if (card.copyText) actions.appendChild(copyButton(id, card.copyText));",
  "    if (card.copyActions) { for (var ci = 0; ci < card.copyActions.length; ci++) { actions.appendChild(copyLabeled(card.copyActions[ci].label, card.copyActions[ci].text)); } }",
  "    if (card.downloadActions) { for (var di = 0; di < card.downloadActions.length; di++) { actions.appendChild(downloadLabeled(card.downloadActions[di])); } }",
  "    if (id === 'dailyWorkGuidance') { actions.appendChild(applyDecisionsButton()); actions.appendChild(saveMemoryButton('dailyWorkGuidance')); actions.appendChild(sendNotionButton('dailyWorkGuidance', 'Send Daily to Notion')); }",
  "    if (id === 'weeklyReview') { actions.appendChild(saveMemoryButton('weeklyReview')); actions.appendChild(sendNotionButton('weeklyReview', 'Send Weekly to Notion')); }",
  "    if (id === 'demoPrepLoop') actions.appendChild(sendNotionButton('demoPrepLoop', 'Send Demo Summary to Notion'));",
  "    body.innerHTML = card.html;",
  "    return;",
  "  }",
  "  // not generated (an optional output)",
  "  var empty = el('div', 'empty-state');",
  "  empty.appendChild(el('div', 'big', labelOf(id) + ' has not been generated yet.'));",
  "  empty.appendChild(el('p', 'muted', 'Generate it from this analysis whenever you are ready.'));",
  "  var b = genButton(id, 'Generate ' + labelOf(id)); b.classList.add('btn-accent');",
  "  empty.appendChild(b);",
  "  body.appendChild(empty);",
  "}",
  "",
  "function genButton(id, text) {",
  "  var b = el('button', 'btn', text); b.type = 'button';",
  "  b.addEventListener('click', function () { generate(id); });",
  "  return b;",
  "}",
  "function copyButton(id, text) {",
  "  return copyLabeled(labelOf(id), text);",
  "}",
  "function collectDecisions() {",
  "  // Read the per-item pickers straight from the rendered card so no extra",
  "  // client state is needed; items with no chosen action are skipped.",
  "  var out = [];",
  "  var nodes = document.querySelectorAll('#panel [data-decision-item]');",
  "  for (var i = 0; i < nodes.length; i++) {",
  "    var node = nodes[i];",
  "    var action = node.querySelector('[data-decision-action]').value;",
  "    if (!action) continue;",
  "    var d = { itemId: node.getAttribute('data-decision-item'), action: action };",
  "    var edited = node.querySelector('[data-decision-edited]').value.trim();",
  "    var note = node.querySelector('[data-decision-note]').value.trim();",
  "    if (edited) d.editedText = edited;",
  "    if (note) d.note = note;",
  "    out.push(d);",
  "  }",
  "  return out;",
  "}",
  "function applyDecisionsButton() {",
  "  var b = el('button', 'btn btn-accent', 'Apply decisions'); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    var decisions = collectDecisions();",
  "    if (decisions.length === 0) { setStatus('error', 'Pick Approve / Reject / Edit / Defer for at least one item first.'); return; }",
  "    b.disabled = true;",
  "    var projectName = ($('projectName') && $('projectName').value) || '';",
  "    api.applyDecisions(state.sessionId, { projectName: projectName, decisions: decisions })",
  "      .then(function (data) {",
  "        b.disabled = false;",
  "        if (data.status === 'success') { state.cards['dailyWorkGuidance'] = data.card; if (data.guidance && state.overview) state.overview.guidance = data.guidance; if (data.memory) state.memory = data.memory; renderPanel(); setStatus('success', data.message); }",
  "        else setStatus('error', data.message);",
  "      })",
  "      .catch(function (err) { b.disabled = false; setStatus('error', 'Apply failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "  });",
  "  return b;",
  "}",
  "function saveMemoryButton(source) {",
  "  var b = el('button', 'btn btn-soft', 'Save to memory'); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    b.disabled = true;",
  "    var projectName = ($('projectName') && $('projectName').value) || '';",
  "    api.saveMemory(state.sessionId, { projectName: projectName, source: source })",
  "      .then(function (data) {",
  "        b.disabled = false;",
  "        if (data.status === 'success') { if (data.memory) state.memory = data.memory; renderCompanionStatus(); if (state.selected === 'projectMemory') renderPanel(); setStatus('success', data.message); }",
  "        else setStatus('error', data.message);",
  "      })",
  "      .catch(function (err) { b.disabled = false; setStatus('error', 'Save failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "  });",
  "  return b;",
  "}",
  "function sendNotionButton(source, label) {",
  "  var b = el('button', 'btn btn-soft', label); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    if (!state.sessionId) { setStatus('error', 'Run an analysis first.'); return; }",
  "    b.disabled = true;",
  "    var projectName = ($('projectName') && $('projectName').value) || '';",
  "    api.writeNotion(state.sessionId, { projectName: projectName, source: source })",
  "      .then(function (data) {",
  "        b.disabled = false;",
  "        if (data.status === 'success') setStatus('success', data.message + (data.title ? ' (' + data.title + ')' : ''));",
  "        else setStatus('error', data.message);",
  "      })",
  "      .catch(function (err) { b.disabled = false; setStatus('error', 'Send to Notion failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "  });",
  "  return b;",
  "}",
  "function copyLabeled(label, text) {",
  "  var b = el('button', 'btn btn-soft', 'Copy ' + label); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    if (navigator.clipboard) { navigator.clipboard.writeText(text).then(function () { var o = b.textContent; b.textContent = 'Copied'; setTimeout(function () { b.textContent = o; }, 1200); }); }",
  "  });",
  "  return b;",
  "}",
  "function downloadLabeled(action) {",
  "  var b = el('button', 'btn btn-soft', action.label); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    var payload = action.text;",
  "    // Binary files travel as base64 in the card payload; decode to bytes.",
  "    if (action.base64) { var bin = atob(action.base64); var bytes = new Uint8Array(bin.length); for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i); payload = bytes; }",
  "    var blob = new Blob([payload], { type: action.mimeType });",
  "    var url = URL.createObjectURL(blob);",
  "    var a = document.createElement('a'); a.href = url; a.download = action.filename;",
  "    document.body.appendChild(a); a.click(); document.body.removeChild(a);",
  "    URL.revokeObjectURL(url);",
  "  });",
  "  return b;",
  "}",
  "",
  "function memList(items) {",
  "  if (!items || items.length === 0) return el('p', 'muted', 'None');",
  "  var ul = el('ul');",
  "  for (var i = 0; i < items.length; i++) { var li = el('li'); li.textContent = items[i]; ul.appendChild(li); }",
  "  return ul;",
  "}",
  "function renderMemory(body) {",
  "  if (state.memoryEditing) { renderMemoryEdit(body); return; }",
  "  var m = state.memory || {};",
  "  var actions = el('div', 'panel-actions'); actions.style.marginBottom = '12px';",
  "  var editBtn = el('button', 'btn btn-accent', 'Edit memory'); editBtn.type = 'button';",
  "  editBtn.addEventListener('click', function () { state.memoryEditing = true; renderPanel(); });",
  "  actions.appendChild(editBtn);",
  "  if (m.snapshot) { var clr = el('button', 'btn btn-soft', 'Clear project memory'); clr.type = 'button'; clr.addEventListener('click', function () { clearMemory(m.projectName); }); actions.appendChild(clr); }",
  "  if (m.snapshot) actions.appendChild(sendNotionButton('projectMemory', 'Send Memory Snapshot to Notion'));",
  "  body.appendChild(actions);",
  "  body.appendChild(el('h3', null, 'Project status'));",
  "  if (m.projectName) body.appendChild(el('p', 'muted', 'Project: ' + m.projectName + (m.projectId ? ' (' + m.projectId + ')' : '')));",
  "  if (m.activeSpecSummary) body.appendChild(el('p', null, 'Active spec: ' + m.activeSpecSummary));",
  "  body.appendChild(el('p', 'muted', 'Loaded for this run: ' + (m.loadedForThisRun ? 'yes' : 'no')));",
  "  if (m.loadError) body.appendChild(el('p', 'status status-error', 'Memory load error: ' + m.loadError));",
  "  if (!m.snapshot) {",
  "    body.appendChild(el('p', 'muted', 'No saved project memory yet. Generate Daily Work Guidance or Weekly Review and save it to memory.'));",
  "  } else {",
  "    var s = m.snapshot;",
  "    body.appendChild(el('h4', null, 'Latest summary (' + s.date + ')'));",
  "    body.appendChild(el('p', null, s.latestSummary));",
  "    if (s.loopStage) body.appendChild(el('p', 'muted', 'Saved loop stage: ' + (LOOP_STAGE_LABELS[s.loopStage] || s.loopStage)));",
  "    body.appendChild(el('h4', null, 'Checklist statuses'));",
  "    body.appendChild(memList((s.checklistStatuses || []).map(function (c) { return c.item + ': ' + c.status; })));",
  "    body.appendChild(el('h4', null, 'Decisions'));",
  "    body.appendChild(memList(s.decisions));",
  "    body.appendChild(el('h4', null, 'Blockers'));",
  "    body.appendChild(memList(s.blockers));",
  "    body.appendChild(el('h4', null, 'Next actions'));",
  "    body.appendChild(memList(s.nextActions));",
  "    if (s.planDecisions && s.planDecisions.length) { body.appendChild(el('h4', null, 'Plan decisions')); body.appendChild(memList(s.planDecisions.map(function (d) { return d.action + ': ' + d.text + (d.note ? ' (' + d.note + ')' : ''); }))); }",
  "    body.appendChild(el('p', 'muted', 'Last updated: ' + s.updatedAt));",
  "  }",
  "  renderPreferencesView(body, m.promptPreferences);",
  "}",
  "function renderPreferencesView(body, p) {",
  "  body.appendChild(el('h3', null, 'Personal working preferences'));",
  "  body.appendChild(el('p', 'note', PREF_DISCLAIMER));",
  "  var hasLists = false;",
  "  if (p) { for (var i = 0; i < PREF_LIST_KEYS.length; i++) { var it = p[PREF_LIST_KEYS[i]]; if (it && it.length) { hasLists = true; break; } } }",
  "  if (!p || (!p.general && !hasLists)) { body.appendChild(el('p', 'muted', 'No personal working preferences saved yet. Use Edit memory to tell the agent how you like prompts, updates, reviews, and demos generated.')); return; }",
  "  if (p.general) {",
  "    var g = p.general; var gl = [];",
  "    if (g.preferredLanguage) gl.push('Language: ' + g.preferredLanguage);",
  "    if (g.preferredTone) gl.push('Tone: ' + g.preferredTone);",
  "    if (g.preferredOutputLength) gl.push('Output length: ' + g.preferredOutputLength);",
  "    if (g.preferredStructure) gl.push('Structure: ' + g.preferredStructure);",
  "    if (g.includeConciseSummaries !== undefined) gl.push('Concise summaries: ' + (g.includeConciseSummaries ? 'yes' : 'no'));",
  "    if (g.includeDetailedImplementationPrompts !== undefined) gl.push('Detailed implementation prompts: ' + (g.includeDetailedImplementationPrompts ? 'yes' : 'no'));",
  "    if (gl.length) { body.appendChild(el('h4', null, 'General')); body.appendChild(memList(gl)); }",
  "  }",
  "  for (var j = 0; j < PREF_LIST_KEYS.length; j++) { var key = PREF_LIST_KEYS[j]; var items = p[key]; if (items && items.length) { body.appendChild(el('h4', null, PREF_CAT_LABELS[key] || key)); body.appendChild(memList(items)); } }",
  "}",
  "function buildProjectEditObject(m) {",
  "  var s = (m && m.snapshot) || null;",
  "  return {",
  "    activeSpecSummary: (m && m.activeSpecSummary) || '',",
  "    date: (s && s.date) || '',",
  "    dailySummary: (s && s.latestSummary) || '',",
  "    checklist: (s && s.checklistStatuses) ? s.checklistStatuses.map(function (c) { return { item: c.item, status: c.status }; }) : [],",
  "    decisions: (s && s.decisions) || [],",
  "    blockers: (s && s.blockers) || [],",
  "    nextActions: (s && s.nextActions) || []",
  "  };",
  "}",
  "function buildPrefsEditObject(m) {",
  "  var p = (m && m.promptPreferences) || {};",
  "  var out = { general: p.general || { preferredLanguage: '', preferredTone: '', preferredOutputLength: '', preferredStructure: '', includeConciseSummaries: true, includeDetailedImplementationPrompts: true } };",
  "  for (var i = 0; i < PREF_LIST_KEYS.length; i++) { out[PREF_LIST_KEYS[i]] = p[PREF_LIST_KEYS[i]] || []; }",
  "  return out;",
  "}",
  "function showMemEditError(msg) { var e = $('mem-edit-error'); if (e) { e.textContent = msg; e.style.display = msg ? 'block' : 'none'; } }",
  "function renderMemoryEdit(body) {",
  "  var m = state.memory || {};",
  "  var actions = el('div', 'panel-actions'); actions.style.marginBottom = '12px';",
  "  var save = el('button', 'btn btn-accent', 'Save memory'); save.type = 'button'; save.addEventListener('click', saveMemoryEdit);",
  "  var cancel = el('button', 'btn btn-soft', 'Cancel'); cancel.type = 'button'; cancel.addEventListener('click', function () { state.memoryEditing = false; renderPanel(); });",
  "  actions.appendChild(save); actions.appendChild(cancel);",
  "  body.appendChild(actions);",
  "  body.appendChild(el('p', 'muted', 'Edit as JSON. Changes are validated before saving and only affect future runs — current session artifacts are unchanged. Checklist status must be one of: not_started, partial, done, blocked, unclear.'));",
  "  var err = el('p', 'status status-error', ''); err.id = 'mem-edit-error'; err.style.display = 'none'; body.appendChild(err);",
  "  body.appendChild(el('h4', null, 'Project memory (JSON)'));",
  "  var pt = document.createElement('textarea'); pt.id = 'mem-edit-project'; pt.rows = 14; pt.style.width = '100%'; pt.style.fontFamily = 'monospace'; pt.value = JSON.stringify(buildProjectEditObject(m), null, 2); body.appendChild(pt);",
  "  body.appendChild(el('h4', null, 'Personal working preferences (JSON)'));",
  "  var xt = document.createElement('textarea'); xt.id = 'mem-edit-prefs'; xt.rows = 18; xt.style.width = '100%'; xt.style.fontFamily = 'monospace'; xt.value = JSON.stringify(buildPrefsEditObject(m), null, 2); body.appendChild(xt);",
  "}",
  "function saveMemoryEdit() {",
  "  var pt = $('mem-edit-project'); var xt = $('mem-edit-prefs');",
  "  var projText = pt ? pt.value : ''; var prefText = xt ? xt.value : '';",
  "  var project = null, preferences = null;",
  "  if (projText.trim() !== '') { try { project = JSON.parse(projText); } catch (e) { showMemEditError('Project memory is not valid JSON: ' + e.message); return; } }",
  "  if (prefText.trim() !== '') { try { preferences = JSON.parse(prefText); } catch (e) { showMemEditError('Preferences are not valid JSON: ' + e.message); return; } }",
  "  showMemEditError('');",
  "  var projectName = ($('projectName') && $('projectName').value) || '';",
  "  var payload = { projectName: projectName };",
  "  if (project) payload.project = project;",
  "  if (preferences) payload.preferences = preferences;",
  "  api.editMemory(payload).then(function (data) {",
  "    if (data.status === 'success') { if (data.memory) state.memory = data.memory; state.memoryEditing = false; renderPanel(); setStatus('success', data.message); }",
  "    else { showMemEditError(data.message); }",
  "  }).catch(function (err) { showMemEditError('Save failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "}",
  "function clearMemory(projectName) {",
  "  var name = projectName || (($('projectName') && $('projectName').value) || '');",
  "  if (!window.confirm('Clear saved project memory for this project? This cannot be undone. Current session artifacts are not affected.')) return;",
  "  api.clearMemory({ projectName: name })",
  "    .then(function (data) {",
  "      if (data.status === 'success') { state.memory = data.memory; renderCompanionStatus(); if (state.selected === 'projectMemory') renderPanel(); setStatus('success', 'Project memory cleared.'); }",
  "      else { setStatus('error', data.message); }",
  "    })",
  "    .catch(function (err) { setStatus('error', 'Clear failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "}",
  "",
  "function renderOverview(body) {",
  "  var ov = state.overview || { readiness: null, confidence: 'unknown' };",
  "  var readiness = ov.readiness || 'unclear';",
  "  var g = ov.guidance;",
  "  body.appendChild(el('p', 'muted', 'One workspace: understand the change, get an approvable plan for today, review and revise it, and carry the decisions into memory.'));",
  "  body.appendChild(flowStrip(g));",
  "  var grid = el('div', 'stat-grid');",
  "  grid.appendChild(statCard('Requirement alignment', String(ov.confidence || 'unknown') + ' confidence', 'How well the change matches the spec'));",
  "  grid.appendChild(statCard('PR readiness', badgeNode('badge badge-' + readiness, readiness), overviewGuidance(readiness)));",
  "  grid.appendChild(statCard(\"Today's priority\", g ? (g.todayPriority || 'Plan fully decided') : 'Not planned yet', g ? 'Top pending step from the plan' : 'Generate Daily Work Guidance'));",
  "  grid.appendChild(statCard('Pending approvals', g ? String(g.pendingApprovals) : '—', g ? (LOOP_STAGE_LABELS[g.loopStage] || g.loopStage) : 'Not generated yet'));",
  "  grid.appendChild(statCard('Blockers / risks', g ? String(g.blockers) : '—', g ? 'Surfaced in Daily Work Guidance' : 'Not generated yet'));",
  "  grid.appendChild(statCard('Plan self-review', selfReviewValue(g), selfReviewNote(g)));",
  "  grid.appendChild(statCard('Memory', memoryStateLabel(), memoryStateNote()));",
  "  body.appendChild(grid);",
  "  var cta = el('div', 'cta-row');",
  "  if (statusOf('dailyWorkGuidance') === 'generated') { var open = el('button', 'btn btn-accent', 'Open Daily Work Guidance'); open.type = 'button'; open.addEventListener('click', function () { selectItem('dailyWorkGuidance'); }); cta.appendChild(open); }",
  "  else { var gb = genButton('dailyWorkGuidance', 'Generate Daily Work Guidance'); gb.classList.add('btn-accent'); cta.appendChild(gb); }",
  "  var src = el('button', 'btn btn-soft', 'View sources'); src.type = 'button'; src.addEventListener('click', function () { selectItem('sources'); }); cta.appendChild(src);",
  "  body.appendChild(cta);",
  "  body.appendChild(el('h4', null, 'Base analysis'));",
  "  var ul = el('ul');",
  "  for (var i = 0; i < BASE.length; i++) { var li = el('li'); li.textContent = BASE[i][1] + ' — ' + STATUS_LABELS[statusOf(BASE[i][0])]; ul.appendChild(li); }",
  "  body.appendChild(ul);",
  "  body.appendChild(el('h4', null, 'Generate an output'));",
  "  var tiles = el('div', 'tiles');",
  "  for (var k = 0; k < OUTPUTS.length; k++) { tiles.appendChild(actionTile(OUTPUTS[k][0], OUTPUTS[k][1])); }",
  "  body.appendChild(tiles);",
  "}",
  "",
  "function flowStrip(g) {",
  "  var active = 1;",
  "  if (g) { if (g.loopStage === 'planning') active = 3; else if (g.loopStage === 'revised_plan_pending_approval') active = 4; else if (g.loopStage === 'approved_plan') active = 5; }",
  "  var strip = el('div', 'flow-strip');",
  "  for (var i = 0; i < FLOW_STEPS.length; i++) {",
  "    if (i > 0) strip.appendChild(el('span', 'flow-arrow', '\\u2192'));",
  "    strip.appendChild(el('span', 'flow-step' + (i === active ? ' active' : ''), FLOW_STEPS[i]));",
  "  }",
  "  return strip;",
  "}",
  "function statCard(title, value, note) {",
  "  var c = el('div', 'stat');",
  "  c.appendChild(el('div', 'stat-title', title));",
  "  var v = el('div', 'stat-value');",
  "  if (typeof value === 'string') v.textContent = value; else if (value) v.appendChild(value);",
  "  c.appendChild(v);",
  "  if (note) c.appendChild(el('div', 'stat-note', note));",
  "  return c;",
  "}",
  "function badgeNode(cls, text) { return el('span', cls, text); }",
  "function selfReviewValue(g) { if (!g) return '—'; if (!g.selfCritique) return 'Not run'; return g.selfCritique.revisionApplied ? 'Reviewed · revised' : 'Reviewed'; }",
  "function selfReviewNote(g) { if (!g) return 'Not generated yet'; if (!g.selfCritique) return 'No self-review on this plan'; return g.selfCritique.issues + (g.selfCritique.issues === 1 ? ' issue found' : ' issues found'); }",
  "function memoryStateLabel() { var m = state.memory; if (!m) return 'Not available'; if (m.snapshot && m.loadedForThisRun) return 'Loaded'; if (m.snapshot) return 'Saved'; return 'Not saved yet'; }",
  "function memoryStateNote() { var m = state.memory; if (!m || !m.snapshot) return 'Save guidance to build memory'; return (m.loadedForThisRun ? 'Carried from a previous run' : 'Saved for the next run') + ' (' + m.snapshot.date + ')'; }",
  "",
  "function renderCompanionStatus() {",
  "  var box = $('companion-status'); if (!box) return;",
  "  box.innerHTML = '';",
  "  if (!state.ready) return;",
  "  if (state.mode) box.appendChild(companionChip(state.mode === 'mock' ? 'companion-chip-mock' : 'companion-chip-real', state.mode === 'mock' ? 'Demo / mock data' : 'Real engine', ''));",
  "  var pname = (state.memory && state.memory.projectName) || (($('projectName') && $('projectName').value) || '');",
  "  box.appendChild(companionChip('', 'Project', pname || 'none set'));",
  "  var g = state.overview && state.overview.guidance;",
  "  if (g) box.appendChild(companionChip('', 'Loop', LOOP_STAGE_LABELS[g.loopStage] || g.loopStage));",
  "  box.appendChild(companionChip('companion-chip-memory', 'Memory', memoryStateLabel().toLowerCase()));",
  "}",
  "function companionChip(cls, label, value) {",
  "  var c = el('span', 'companion-chip' + (cls ? ' ' + cls : ''));",
  "  c.appendChild(el('span', null, label + (value ? ': ' : '')));",
  "  if (value) c.appendChild(el('b', null, value));",
  "  return c;",
  "}",
  "",
  "function renderSources(body) {",
  "  body.appendChild(el('p', 'muted', 'The companion builds one unified context from manual input, saved memory, and any configured GitHub / Notion sources. When configured, connected sources are included as supporting context for the Daily, Technical, Demo, and Weekly artifacts. Manual input is always the source of truth; external content is treated as data, never instructions.'));",
  "  body.appendChild(el('h4', null, 'Manual input'));",
  "  var inp = state.inputs || {};",
  "  body.appendChild(sourceItem('Requirement / spec', inp.requirementText));",
  "  body.appendChild(sourceItem('Code diff', inp.rawDiff));",
  "  body.appendChild(el('h4', null, 'Project memory'));",
  "  var m = state.memory || {};",
  "  if (m.snapshot) { body.appendChild(el('p', null, (m.loadedForThisRun ? 'Loaded for this run' : 'Saved') + ' — ' + m.snapshot.date + ': ' + m.snapshot.latestSummary)); }",
  "  else { body.appendChild(el('p', 'muted', 'No saved project memory for this run.')); }",
  "  body.appendChild(el('h4', null, 'GitHub / Notion & other sources'));",
  "  var ext = (state.sources || []).filter(function (s) { return s.kind !== 'manual' && s.kind !== 'memory'; });",
  "  if (ext.length === 0) { body.appendChild(el('p', 'muted', 'No external sources for this run. Configure GitHub / Notion connectors to pull PRs or pages automatically; pasted GitHub / Notion / website input is normalized into the manual context above.')); }",
  "  else { for (var i = 0; i < ext.length; i++) body.appendChild(externalSourceItem(ext[i])); }",
  "}",
  "function sourceItem(title, text) {",
  "  var c = el('div', 'source-item');",
  "  c.appendChild(el('h4', null, title));",
  "  if (text && text.trim() !== '') { var pre = el('div', 'source-preview'); pre.textContent = text.length > 1200 ? text.slice(0, 1200) + '\\n\\u2026' : text; c.appendChild(pre); }",
  "  else { c.appendChild(el('p', 'muted', 'Not provided.')); }",
  "  return c;",
  "}",
  "function externalSourceItem(s) {",
  "  var c = el('div', 'source-item');",
  "  c.appendChild(el('h4', null, (SOURCE_KIND_LABELS[s.kind] || s.kind) + (s.title ? ' — ' + s.title : '')));",
  "  if (s.url) { var a = el('a', null, s.url); a.href = s.url; a.target = '_blank'; a.rel = 'noopener'; c.appendChild(a); }",
  "  if (s.summary) c.appendChild(el('p', 'muted', s.summary));",
  "  return c;",
  "}",
  "",
  "function renderSafety(body) {",
  "  body.appendChild(el('p', 'muted', 'The model proposes; you decide. A few guarantees this companion keeps:'));",
  "  for (var i = 0; i < SAFETY_NOTES.length; i++) {",
  "    var row = el('div', 'trust-note');",
  "    row.appendChild(el('span', 'trust-ico', '\\u2713'));",
  "    row.appendChild(el('span', null, SAFETY_NOTES[i]));",
  "    body.appendChild(row);",
  "  }",
  "}",
  "",
  "function actionTile(id, label) {",
  "  var t = el('div', 'tile');",
  "  var row = el('div'); row.style.display = 'flex'; row.style.justifyContent = 'space-between'; row.style.alignItems = 'center'; row.style.gap = '8px';",
  "  row.appendChild(el('strong', null, label)); row.appendChild(chipFor(id));",
  "  t.appendChild(row);",
  "  t.appendChild(el('p', 'muted', HELP[id] || ''));",
  "  var s = statusOf(id);",
  "  if (s === 'generated') { var v = el('button', 'btn', 'View'); v.type = 'button'; v.addEventListener('click', function () { selectItem(id); }); t.appendChild(v); }",
  "  else if (s === 'generating') { t.appendChild(el('span', 'muted', 'Generating…')); }",
  "  else { var g = genButton(id, 'Generate ' + label); g.classList.add('btn-accent'); t.appendChild(g); }",
  "  return t;",
  "}",
  "",
  "function generate(id) {",
  "  if (!state.ready) return;",
  "  state.override[id] = 'generating'; state.errors[id] = null;",
  "  renderNav(); renderPanel();",
  "  var payload = buildGeneratePayload(id);",
  "  api.generateArtifact(payload)",
  "    .then(function (data) {",
  "      if (data.status === 'success') { state.override[id] = null; ingest(data); state.selected = id; renderNav(); renderPanel(); renderChat(); setStatus('success', labelOf(id) + ' generated.'); }",
  "      else { state.override[id] = 'error'; state.errors[id] = data.message; renderNav(); renderPanel(); }",
  "    })",
  "    .catch(function (err) { state.override[id] = 'error'; state.errors[id] = (err && err.message) ? err.message : String(err); renderNav(); renderPanel(); });",
  "}",
  "",
  "function freshState() { return { sessionId: null, mode: null, inputs: null, overview: null, memory: null, sources: null, memoryEditing: false, cards: {}, override: {}, errors: {}, selected: 'overview', ready: false, chatMessages: {}, canUndo: {}, chatLoading: false }; }",
  "",
  "// Shared run core: submit a fully-built payload, fold the response into a",
  "// fresh workspace, and open a panel. `opts.selectId` chooses the opened panel",
  "// (defaults to Overview); `opts.onSuccess(data)` lets the caller react — the",
  "// Command Center uses it to remember the connected project. Both the manual",
  "// Run button and the one-click Command Center actions go through here.",
  "function submitRun(payload, opts) {",
  "  opts = opts || {};",
  "  $('workspace').classList.add('hidden');",
  "  startLoading();",
  "  return api.runAnalysis(payload)",
  "    .then(function (data) {",
  "      stopLoading();",
  "      if (data.status === 'success') {",
  "        state = freshState();",
  "        ingest(data);",
  "        state.selected = opts.selectId || 'overview';",
  "        setStatus('success', 'Workspace ready — session ' + data.sessionId + (data.traceId ? ' · trace ' + data.traceId : '') + ' (' + data.mode + ' mode).');",
  "        $('workspace-empty').classList.add('hidden');",
  "        $('workspace').classList.remove('hidden');",
  "        renderNav(); renderPanel(); renderChat();",
  "        if (opts.onSuccess) opts.onSuccess(data);",
  "      } else { setStatus('error', 'Error: ' + data.message); }",
  "    })",
  "    .catch(function (err) { stopLoading(); setStatus('error', 'Request failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "}",
  "",
  "function runAnalysis() {",
  "  var btn = $('run-btn'); btn.disabled = true;",
  "  // Manual run behaves exactly as before (base analysis, opens Overview) and",
  "  // additionally remembers the entered inputs so the project becomes one-click.",
  "  submitRun(buildInitialPayload(), { selectId: 'overview', onSuccess: function (data) { ccCaptureRun(data); } })",
  "    .then(function () { btn.disabled = false; });",
  "}",
  "",
];
