/**
 * Client app: the analysis workspace controller.
 *
 * Owns the workspace interactions and its main view:
 *   - request builders for `/api/analyze` (initial run vs. on-demand generation);
 *   - `ingest`, which folds an analyze response into state;
 *   - the content panel + Overview + per-output action tiles;
 *   - the `generate` (on-demand) and `runAnalysis` (initial) flows.
 *
 * It calls `api.*` for the network and the shared render helpers for the DOM;
 * it never embeds endpoint URLs.
 */
export const WORKSPACE_LINES: string[] = [
  "function buildInitialPayload() {",
  "  var mode = currentMode();",
  "  var p = { inputMode: mode, projectName: $('projectName').value };",
  "  // Initial analysis runs ONLY the base understanding artifacts. Optional",
  "  // communication outputs are generated later, on demand.",
  "  p.includeFlow = true; p.includeGapReport = true;",
  "  p.includePrDescription = false; p.includeVideoScript = false; p.includeDailyUpdate = false; p.includeDailyWorkGuidance = false; p.includeTechnicalChangeBrief = false; p.includeDemoPrepLoop = false; p.includeWeeklyReview = false;",
  "  if (mode === 'manual') { p.requirementText = $('requirementText').value; p.rawDiff = $('rawDiff').value; }",
  "  else if (mode === 'githubUrl') { p.githubUrl = $('githubUrl').value; p.requirementText = $('gh_requirementText').value; }",
  "  else if (mode === 'websiteContextUrl') { p.websiteUrl = $('websiteUrl').value; p.rawDiff = $('ws_rawDiff').value; }",
  "  else if (mode === 'notionText') { p.notionText = $('notionText').value; p.rawDiff = $('nt_rawDiff').value; }",
  "  return p;",
  "}",
  "",
  "function buildGeneratePayload(targetId) {",
  "  // Re-send the resolved inputs as manual + sessionId so the engine reuses",
  "  // the session and only runs the new skill (no re-fetch, no recompute).",
  "  var p = { inputMode: 'manual', sessionId: state.sessionId, requirementText: state.inputs.requirementText, rawDiff: state.inputs.rawDiff };",
  "  p.includeFlow = true; p.includeGapReport = true;",
  "  p.includePrDescription = false; p.includeVideoScript = false; p.includeDailyUpdate = false; p.includeDailyWorkGuidance = false; p.includeTechnicalChangeBrief = false; p.includeDemoPrepLoop = false; p.includeWeeklyReview = false;",
  "  var keep = ['prDescription','videoScript','dailyUpdate','dailyWorkGuidance','technicalChangeBrief','demoPrepLoop','weeklyReview'];",
  "  for (var i = 0; i < keep.length; i++) { if (statusOf(keep[i]) === 'generated') p[FLAG_OF[keep[i]]] = true; }",
  "  var add = [targetId].concat(DEPS[targetId] || []);",
  "  for (var j = 0; j < add.length; j++) { if (FLAG_OF[add[j]]) p[FLAG_OF[add[j]]] = true; }",
  "  return p;",
  "}",
  "",
  "function ingest(data) {",
  "  state.sessionId = data.sessionId;",
  "  state.mode = data.mode;",
  "  state.inputs = data.inputs;",
  "  state.overview = data.overview;",
  "  for (var i = 0; i < data.cards.length; i++) { state.cards[data.cards[i].id] = data.cards[i]; }",
  "  state.ready = true;",
  "}",
  "",
  "function labelOf(id) {",
  "  if (id === 'overview') return 'Overview';",
  "  if (id === 'rawJson') return 'Raw JSON';",
  "  var all = BASE.concat(OUTPUTS);",
  "  for (var i = 0; i < all.length; i++) if (all[i][0] === id) return all[i][1];",
  "  return id;",
  "}",
  "",
  "function renderPanel() {",
  "  var panel = $('panel');",
  "  var id = state.selected;",
  "  var grp = id === 'overview' ? 'overview' : (GROUP_OF[id] || 'understanding');",
  "  panel.className = 'panel panel-accent-' + grp;",
  "  panel.innerHTML = '';",
  "  var head = el('div', 'panel-head');",
  "  var titleWrap = el('div');",
  "  titleWrap.appendChild(el('h2', 'panel-title', labelOf(id)));",
  "  titleWrap.appendChild(el('p', 'panel-desc', HELP[id] || ''));",
  "  head.appendChild(titleWrap);",
  "  var actions = el('div', 'panel-actions');",
  "  head.appendChild(actions);",
  "  panel.appendChild(head);",
  "  var body = el('div', 'panel-body');",
  "  panel.appendChild(body);",
  "",
  "  if (id === 'overview') { renderOverview(body); return; }",
  "",
  "  var s = statusOf(id);",
  "  if (s === 'generating') { body.appendChild(el('p', 'muted', 'Generating ' + labelOf(id) + '… this can take a little while.')); return; }",
  "  if (s === 'error') {",
  "    body.appendChild(el('p', 'status status-error', 'Error: ' + (state.errors[id] || 'generation failed')));",
  "    actions.appendChild(genButton(id, 'Try again'));",
  "    return;",
  "  }",
  "  var card = state.cards[id];",
  "  if (s === 'generated' && card) {",
  "    if (card.copyText) actions.appendChild(copyButton(id, card.copyText));",
  "    if (card.copyActions) { for (var ci = 0; ci < card.copyActions.length; ci++) { actions.appendChild(copyLabeled(card.copyActions[ci].label, card.copyActions[ci].text)); } }",
  "    if (card.downloadAction) { actions.appendChild(downloadLabeled(card.downloadAction.label, card.downloadAction.filename, card.downloadAction.text)); }",
  "    if (id === 'dailyWorkGuidance') actions.appendChild(saveMemoryButton('dailyWorkGuidance'));",
  "    if (id === 'weeklyReview') actions.appendChild(saveMemoryButton('weeklyReview'));",
  "    body.innerHTML = card.html;",
  "    return;",
  "  }",
  "  // not generated (an optional output)",
  "  var empty = el('div', 'empty-state');",
  "  empty.appendChild(el('div', 'big', labelOf(id) + ' has not been generated yet.'));",
  "  empty.appendChild(el('p', 'muted', 'Generate it from this analysis whenever you are ready.'));",
  "  var b = genButton(id, 'Generate ' + labelOf(id)); b.classList.add('btn-accent');",
  "  empty.appendChild(b);",
  "  body.appendChild(empty);",
  "}",
  "",
  "function genButton(id, text) {",
  "  var b = el('button', 'btn', text); b.type = 'button';",
  "  b.addEventListener('click', function () { generate(id); });",
  "  return b;",
  "}",
  "function copyButton(id, text) {",
  "  return copyLabeled(labelOf(id), text);",
  "}",
  "function saveMemoryButton(source) {",
  "  var b = el('button', 'btn btn-soft', 'Save to memory'); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    b.disabled = true;",
  "    var projectName = ($('projectName') && $('projectName').value) || '';",
  "    api.saveMemory(state.sessionId, { projectName: projectName, source: source })",
  "      .then(function (data) {",
  "        b.disabled = false;",
  "        if (data.status === 'success') setStatus('success', data.message);",
  "        else setStatus('error', data.message);",
  "      })",
  "      .catch(function (err) { b.disabled = false; setStatus('error', 'Save failed: ' + ((err && err.message) ? err.message : String(err))); });",
  "  });",
  "  return b;",
  "}",
  "function copyLabeled(label, text) {",
  "  var b = el('button', 'btn btn-soft', 'Copy ' + label); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    if (navigator.clipboard) { navigator.clipboard.writeText(text).then(function () { var o = b.textContent; b.textContent = 'Copied'; setTimeout(function () { b.textContent = o; }, 1200); }); }",
  "  });",
  "  return b;",
  "}",
  "function downloadLabeled(label, filename, text) {",
  "  var b = el('button', 'btn btn-soft', label); b.type = 'button';",
  "  b.addEventListener('click', function () {",
  "    var blob = new Blob([text], { type: 'text/markdown' });",
  "    var url = URL.createObjectURL(blob);",
  "    var a = document.createElement('a'); a.href = url; a.download = filename;",
  "    document.body.appendChild(a); a.click(); document.body.removeChild(a);",
  "    URL.revokeObjectURL(url);",
  "  });",
  "  return b;",
  "}",
  "",
  "function renderOverview(body) {",
  "  var ov = state.overview || { readiness: null, confidence: 'unknown' };",
  "  var readiness = ov.readiness || 'unclear';",
  "  var head = el('p'); head.innerHTML = 'PR readiness: <span class=\"badge badge-' + readiness + '\">' + readiness + '</span> &nbsp; Requirement confidence: <strong>' + ov.confidence + '</strong>';",
  "  body.appendChild(head);",
  "  body.appendChild(el('p', null, overviewGuidance(readiness)));",
  "  body.appendChild(el('h4', null, 'What was generated'));",
  "  var ul = el('ul');",
  "  var base = BASE;",
  "  for (var i = 0; i < base.length; i++) { var li = el('li'); li.textContent = base[i][1] + ' — ' + STATUS_LABELS[statusOf(base[i][0])]; ul.appendChild(li); }",
  "  body.appendChild(ul);",
  "  body.appendChild(el('h4', null, 'Available next actions'));",
  "  var tiles = el('div', 'tiles');",
  "  for (var k = 0; k < OUTPUTS.length; k++) { tiles.appendChild(actionTile(OUTPUTS[k][0], OUTPUTS[k][1])); }",
  "  body.appendChild(tiles);",
  "}",
  "",
  "function actionTile(id, label) {",
  "  var t = el('div', 'tile');",
  "  var row = el('div'); row.style.display = 'flex'; row.style.justifyContent = 'space-between'; row.style.alignItems = 'center'; row.style.gap = '8px';",
  "  row.appendChild(el('strong', null, label)); row.appendChild(chipFor(id));",
  "  t.appendChild(row);",
  "  t.appendChild(el('p', 'muted', HELP[id] || ''));",
  "  var s = statusOf(id);",
  "  if (s === 'generated') { var v = el('button', 'btn', 'View'); v.type = 'button'; v.addEventListener('click', function () { selectItem(id); }); t.appendChild(v); }",
  "  else if (s === 'generating') { t.appendChild(el('span', 'muted', 'Generating…')); }",
  "  else { var g = genButton(id, 'Generate ' + label); g.classList.add('btn-accent'); t.appendChild(g); }",
  "  return t;",
  "}",
  "",
  "function generate(id) {",
  "  if (!state.ready) return;",
  "  state.override[id] = 'generating'; state.errors[id] = null;",
  "  renderNav(); renderPanel();",
  "  var payload = buildGeneratePayload(id);",
  "  api.generateArtifact(payload)",
  "    .then(function (data) {",
  "      if (data.status === 'success') { state.override[id] = null; ingest(data); state.selected = id; renderNav(); renderPanel(); renderChat(); setStatus('success', labelOf(id) + ' generated.'); }",
  "      else { state.override[id] = 'error'; state.errors[id] = data.message; renderNav(); renderPanel(); }",
  "    })",
  "    .catch(function (err) { state.override[id] = 'error'; state.errors[id] = (err && err.message) ? err.message : String(err); renderNav(); renderPanel(); });",
  "}",
  "",
  "function runAnalysis() {",
  "  var btn = $('run-btn'); btn.disabled = true;",
  "  $('workspace').classList.add('hidden');",
  "  startLoading();",
  "  api.runAnalysis(buildInitialPayload())",
  "    .then(function (data) {",
  "      stopLoading();",
  "      if (data.status === 'success') {",
  "        state = { sessionId: null, mode: null, inputs: null, overview: null, cards: {}, override: {}, errors: {}, selected: 'overview', ready: false, chatMessages: {}, canUndo: {}, chatLoading: false };",
  "        ingest(data);",
  "        setStatus('success', 'Workspace ready — session ' + data.sessionId + ' (' + data.mode + ' mode).');",
  "        $('workspace-empty').classList.add('hidden');",
  "        $('workspace').classList.remove('hidden');",
  "        renderNav(); renderPanel(); renderChat();",
  "      } else { setStatus('error', 'Error: ' + data.message); }",
  "    })",
  "    .catch(function (err) { stopLoading(); setStatus('error', 'Request failed: ' + ((err && err.message) ? err.message : String(err))); })",
  "    .then(function () { btn.disabled = false; });",
  "}",
  "",
];
